<?php
return array(
	'DB_HOST'=>'localhost',
	'DB_USER'=>'root',
	'DB_PASSWD'=>'purple',
	'DB_NAME'=>'360ask',
	//模板公共目录
	'TPL_PUBLIC'=>TEMPLATE_PATH.'Public/',
	'__PUBLIC__'=>'./Public/',
	//字体目录
	'FONT'=>RUN_PATH.'Data/Font/font.ttf',
	//Email配置
	'EMAIL'=>'air_zhe@163.com',
	'EMAIL_PASSWD'=>base64_decode('SGFvemhl'),
	'AUTH_LINK_EXPIRED'=>20,
	//加密密钥
	'TOKEN'=>'houdunwang.com',
	//SESSION_NAME
	'SESSION_NAME'=>md5('houdunwang.com')
	);